-- phpMyAdmin SQL Dump
-- version 4.6.6deb5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 26, 2019 at 09:06 PM
-- Server version: 5.7.27-0ubuntu0.18.04.1
-- PHP Version: 7.2.19-0ubuntu0.18.04.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shoppee`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

CREATE TABLE `cart` (
  `id` int(10) UNSIGNED NOT NULL,
  `productID` int(10) UNSIGNED NOT NULL,
  `name` varchar(30) CHARACTER SET latin1 NOT NULL,
  `price` mediumint(8) UNSIGNED NOT NULL,
  `image` varchar(30) CHARACTER SET latin1 NOT NULL,
  `shortDescription` text CHARACTER SET latin1 NOT NULL,
  `longDescription` text CHARACTER SET latin1 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `orderNumber` int(11) NOT NULL,
  `customerName` text COLLATE utf8_unicode_ci NOT NULL,
  `customerAddress` text COLLATE utf8_unicode_ci NOT NULL,
  `customerCreditCard` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `customerCVV` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `customerExp` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `customerEmail` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `customerPhone` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `customerOrder` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `orders`
--

INSERT INTO `orders` (`orderNumber`, `customerName`, `customerAddress`, `customerCreditCard`, `customerCVV`, `customerExp`, `customerEmail`, `customerPhone`, `customerOrder`) VALUES
(11, 'Ivan Arregoitia', '418 Veneto', '7777777777777777', '7777', '777', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"1\",\"name\":\"Master Sword\",\"price\":\"99999\",\"image\":\"https://bit.ly/2PlzNih\",\"shortDescription\":\"Perfect sword for saving a kingdom trapped in darkness!\",\"longDescription\":\"The Master Sword was originally crafted by the goddess Hylia as the Goddess Sword, and was later forged into the Master Sword by the Goddess chosen hero and its spirit, Fi, who bathed it in the three Sacred Flames located across the land that would become the Kingdom of Hyrule. Dins Flame in particular imbued the sword with the Power to Repel Evil, a power augmented after the Sword received the blessing of Zelda, which transformed the blade into the True Master Sword.\",\"checkoutDescription\":\"\"}]'),
(12, 'Ivan Arregoitia Test', '418 Veneto', '5757575757575757', '1236', '012', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"3\",\"name\":\"Energy Sword\",\"price\":\"99999\",\"image\":\"https://bit.ly/32do72K\",\"shortDescription\":\"A sword radiating and made of pure energy. Ideal for those who want to be able to lunge at their enemies from distance or have as a flashlight.\",\"longDescription\":\"The Type-1 Energy Weapon is an extremely powerful and devastating melee weapon when applied during close quarters combat. A single slash can penetrate through the energy shield systems and into the armor and flesh of a Spartan or a Sangheili. This is due to the design of the weapon\'s blade, which utilizes magnetically sealed, partially ionized, free moving electron based gas rather than traditional shaped, solid matter. The Type-1 Energy Weapon\'s edge is therefore extremely volatile, being able to slice through even the toughest metals with ridiculous ease, including ODST battle armour and the Titanium-A class plating of UNSC destroyers.\",\"checkoutDescription\":\"\"}]'),
(13, 'Ivan Arregoitia', '418 Veneto', '7474744744747444', '74747', '747', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"}]'),
(14, 'Ivan Arregoitia', '418 Veneto', '7474744447477474', '7474', '744', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\",\"checkoutDescription\":\"\"}]'),
(15, 'Ivan Arregoitia', '418 Veneto', '7474747444744747', '7474', '744', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(16, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(17, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(18, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(19, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(20, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(21, 'Ivan Arregoitia', '418 Veneto', '11111111111111111', '', '', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(22, 'Ivan Arregoitia', '418 Veneto', '', '', '', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(23, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(24, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(25, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(26, '', '', '', '', '', '', '', '[{\"id\":\"1\",\"productID\":\"4\",\"name\":\"Keyblade\",\"price\":\"999999\",\"image\":\"https://bit.ly/2UjymA0\",\"shortDescription\":\"A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.\",\"longDescription\":\"The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.\"},{\"id\":\"2\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(27, 'This', '12364 fwefew', '45454545454545454', '4545', '444', 'test@test.com', '7418529634', '[{\"id\":\"3\",\"name\":\"Energy Sword\",\"price\":\"99999\",\"image\":\"https://bit.ly/2kg313y\",\"shortDescription\":\"A sword radiating and made of pure energy. Ideal for those who want to be able to lunge at their enemies from distance or have as a flashlight.\",\"longDescription\":\"The Type-1 Energy Weapon is an extremely powerful and devastating melee weapon when applied during close quarters combat. A single slash can penetrate through the energy shield systems and into the armor and flesh of a Spartan or a Sangheili. This is due to the design of the weapon\'s blade, which utilizes magnetically sealed, partially ionized, free moving electron based gas rather than traditional shaped, solid matter. The Type-1 Energy Weapon\'s edge is therefore extremely volatile, being able to slice through even the toughest metals with ridiculous ease, including ODST battle armour and the Titanium-A class plating of UNSC destroyers.\",\"checkoutDescription\":\"\"}]'),
(28, 'Ivan Arregoitia', '418 Veneto', '1111111111111111', '1111', '111', 'ivanarrego@gmail.com', '7142994219', '[{\"id\":\"1\",\"productID\":\"3\",\"name\":\"Energy Sword\",\"price\":\"99999\",\"image\":\"https://bit.ly/2kg313y\",\"shortDescription\":\"A sword radiating and made of pure energy. Ideal for those who want to be able to lunge at their enemies from distance or have as a flashlight.\",\"longDescription\":\"The Type-1 Energy Weapon is an extremely powerful and devastating melee weapon when applied during close quarters combat. A single slash can penetrate through the energy shield systems and into the armor and flesh of a Spartan or a Sangheili. This is due to the design of the weapon\'s blade, which utilizes magnetically sealed, partially ionized, free moving electron based gas rather than traditional shaped, solid matter. The Type-1 Energy Weapon\'s edge is therefore extremely volatile, being able to slice through even the toughest metals with ridiculous ease, including ODST battle armour and the Titanium-A class plating of UNSC destroyers.\"}]'),
(29, 'hi', '123 any street', '5555555555555555', '0909', '555', 'a@b.cd', '', '[{\"id\":\"5\",\"productID\":\"5\",\"name\":\"Plasma Cutters\",\"price\":\"999999\",\"image\":\"https://bit.ly/349hbp3\",\"shortDescription\":\"A multi-use tool perfect for those who are engineers in a mining exploration or need to cut down their foes.\",\"longDescription\":\"The Plasma Cutter delivers a cohesive pulse-stream, or \\\"bolt\\\", of ionized plasma when fired. It is capable of firing bolts vertically (primary firing mode) and horizontally (secondary firing mode). The Plasma Cutter is very accurate, utilizing three blue lasers to indicate the desired cutting plane.\\r\\n\\r\\nOn impact with the target, bolt cohesion fails frontward first, penetrating the target with a focused jet of superheated matter. This causes intense localized shear effects as well as a tunneling thermal expansion. When used upon brittle, frozen rocks riddled with faults, it can split them open in one or two shots in skilled hands. Against pliable targets, however, impact will cause minimal damage and thermal expansion will not so much cut as stress the area around the impact site, sometimes requiring several consecutive hits with the non-upgraded tool. Still, when presented with a less than effective alternative against dense organic matter, the 211-V Plasma Cutter retains its utility.\"}]'),
(30, 'ivan', '152 qfdwffwf', '1222222222222222', '1212', '111', 'a@gmail.com', '7777777777', '[{\"id\":\"14\",\"productID\":\"2\",\"name\":\"Mark 2 Lancer Assault Rifle\",\"price\":\"99999\",\"image\":\"https://bit.ly/2ZwLzvb\",\"shortDescription\":\"Perfect weapon to take out hordes of enemies or to cut down any obstacles!\",\"longDescription\":\"The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.\"}]'),
(31, 'Ivan', '1234 Here', '4545151511515515', '15/15', '123', 'a@aol.com', '1456621155', '[{\"id\":\"16\",\"productID\":\"1\",\"name\":\"Master Sword\",\"price\":\"99999\",\"image\":\"https://bit.ly/2kb2DTT\",\"shortDescription\":\"Perfect sword for saving a kingdom trapped in darkness!\",\"longDescription\":\"The Master Sword was originally crafted by the goddess Hylia as the Goddess Sword, and was later forged into the Master Sword by the Goddess chosen hero and its spirit, Fi, who bathed it in the three Sacred Flames located across the land that would become the Kingdom of Hyrule. Dins Flame in particular imbued the sword with the Power to Repel Evil, a power augmented after the Sword received the blessing of Zelda, which transformed the blade into the True Master Sword.\"},{\"id\":\"17\",\"productID\":\"3\",\"name\":\"Energy Sword\",\"price\":\"99999\",\"image\":\"https://bit.ly/2kg313y\",\"shortDescription\":\"A sword radiating and made of pure energy. Ideal for those who want to be able to lunge at their enemies from distance or have as a flashlight.\",\"longDescription\":\"The Type-1 Energy Weapon is an extremely powerful and devastating melee weapon when applied during close quarters combat. A single slash can penetrate through the energy shield systems and into the armor and flesh of a Spartan or a Sangheili. This is due to the design of the weapon\'s blade, which utilizes magnetically sealed, partially ionized, free moving electron based gas rather than traditional shaped, solid matter. The Type-1 Energy Weapon\'s edge is therefore extremely volatile, being able to slice through even the toughest metals with ridiculous ease, including ODST battle armour and the Titanium-A class plating of UNSC destroyers.\"}]');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` mediumint(8) UNSIGNED NOT NULL,
  `name` varchar(30) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `price` mediumint(9) NOT NULL,
  `image` varchar(30) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `shortDescription` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `longDescription` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `checkoutDescription` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `price`, `image`, `shortDescription`, `longDescription`, `checkoutDescription`) VALUES
(1, 'Master Sword', 99999, 'https://bit.ly/2kb2DTT', 'Perfect sword for saving a kingdom trapped in darkness!', 'The Master Sword was originally crafted by the goddess Hylia as the Goddess Sword, and was later forged into the Master Sword by the Goddess chosen hero and its spirit, Fi, who bathed it in the three Sacred Flames located across the land that would become the Kingdom of Hyrule. Dins Flame in particular imbued the sword with the Power to Repel Evil, a power augmented after the Sword received the blessing of Zelda, which transformed the blade into the True Master Sword.', ''),
(2, 'Mark 2 Lancer Assault Rifle', 99999, 'https://bit.ly/2ZwLzvb', 'Perfect weapon to take out hordes of enemies or to cut down any obstacles!', 'The Mark 2 Lancer Assault Rifle was the Coalition of Ordered Governments\' current standard-issue assault rifle for Gears fighting on the front lines. The signature weapon of the COG, the Lancer possessed a fully automatic mode of fire and the iconic Chainsaw Bayonet attachment for melee combat, despite the fact that the chainsaw was originally for utility purposes. One of the most popular rifle designs on Sera, the Lancer saw extensive use after the Pendulum Wars. Its long service record was a result of its rugged reliability and reputation as a versatile assault rifle. Although intended for mid-range combat, the Lancer was also effective at longer ranges due to its low recoil.', ''),
(3, 'Energy Sword', 99999, 'https://bit.ly/2kg313y', 'A sword radiating and made of pure energy. Ideal for those who want to be able to lunge at their enemies from distance or have as a flashlight.', 'The Type-1 Energy Weapon is an extremely powerful and devastating melee weapon when applied during close quarters combat. A single slash can penetrate through the energy shield systems and into the armor and flesh of a Spartan or a Sangheili. This is due to the design of the weapon\'s blade, which utilizes magnetically sealed, partially ionized, free moving electron based gas rather than traditional shaped, solid matter. The Type-1 Energy Weapon\'s edge is therefore extremely volatile, being able to slice through even the toughest metals with ridiculous ease, including ODST battle armour and the Titanium-A class plating of UNSC destroyers.', ''),
(4, 'Keyblade', 999999, 'https://bit.ly/2UjymA0', 'A keyblade from the Realm of Light. Perfect for those who need a weapon and don\'t lose their keys.', 'The Kingdom Key draws out the true power of Sora\'s Keyblade, even though it is not the strongest Keychain. As such, it is the true form of his Keyblade, which means that it is also the default form of Roxas\'s and Xion\'s Keyblades. The Kingdom Key is not wielded by Sora exclusively; Riku, Roxas, and Xion have also used it, and King Mickey is often seen wielding the Kingdom Key D, a color-inverted version of the weapon.', ''),
(5, 'Plasma Cutters', 999999, 'https://bit.ly/349hbp3', 'A multi-use tool perfect for those who are engineers in a mining exploration or need to cut down their foes.', 'The Plasma Cutter delivers a cohesive pulse-stream, or \"bolt\", of ionized plasma when fired. It is capable of firing bolts vertically (primary firing mode) and horizontally (secondary firing mode). The Plasma Cutter is very accurate, utilizing three blue lasers to indicate the desired cutting plane.\r\n\r\nOn impact with the target, bolt cohesion fails frontward first, penetrating the target with a focused jet of superheated matter. This causes intense localized shear effects as well as a tunneling thermal expansion. When used upon brittle, frozen rocks riddled with faults, it can split them open in one or two shots in skilled hands. Against pliable targets, however, impact will cause minimal damage and thermal expansion will not so much cut as stress the area around the impact site, sometimes requiring several consecutive hits with the non-upgraded tool. Still, when presented with a less than effective alternative against dense organic matter, the 211-V Plasma Cutter retains its utility.', ''),
(6, 'Blue Shell', 99999, 'https://bit.ly/2MLE8ZU', 'Are you competing in a kart race and find yourself not in first? Well now you can take out whoever is i  the lead and give yourself a chance to catch up!', 'In its first appearance, the Spiny Shell is just a blue variant of the more common red Spiny Shell in previous Mario games. Any racer besides first place can obtain it, but it\'s by far the rarest Item in the game. Once obtained from an Item Box and fired, the Spiny Shell travels in a straight path for a few moments. Much like a Red Shell, if the Spiny Shell hits a wall, it\'s gone for good (although it has better corner-careening powers than the Red Shell). After this, the shell locks on to the first place racer, traveling in the middle of the road and bowling over any racers in its path. Any gaps in the track aren\'t a problem for the Spiny Shell; they can simply glide right over them. Once the first place racer hears the siren sound, they\'re knocked over in a violent crash.', ''),
(7, 'Blades of Chaos', 999999, 'https://bit.ly/2kG2ms7', 'The Blades of Chaos are a pair of chained blades that were fashioned by the God of War, Ares. Ares had the blades made for a servant who would prove worthy of his service.', 'The Blades of Chaos were forged at the darkest depths of the Underworld by Ares himself. They were imbued with fire, which allowed them to ignite with every attack that the user performed. The Blades\' chains would stretch out for a set distance with each attack, allowing for fluid movement no matter who wielded them. The chains of the blades were permanently seared onto the forearms of the wielder, which served as a reminder of their oath to the God of War, and could only be removed either by the God of War himself or when the wielder\'s time of servitude ended.', ''),
(8, 'Handheld Portal Device', 9999, 'https://bit.ly/2keed0z', 'The Aperture Science Handheld Portal Device (also known as the Portal Gun, ASHPoD, Aperture Science Quantum Tunneling Device, or ASHPD) is the experimental tool designed to place two portals that objects can pass through. ', 'The Handheld Portal Device is designed to create and place portals on any white surface that is immobile, flat and large enough. When the device is fired, a colored projectile will be emitted from the barrel. If the projectile strikes a valid surface, a portal of the corresponding color will be formed. If a portal of the other color is already placed, these two portals will be linked. If a portal of the same color is already placed, it will be closed and the new one will be used instead, limiting the player to the use of only two portals at a time. Nothing will happen if a portal is shot at an enemy or other object. The glass chamber and a light on the top of the device will glow with the color of the previously placed portal.', ''),
(9, 'Crowbar', 999, 'https://bit.ly/2mabFkD', 'Perfect for bashing foes, opening boxes or cars!', 'Originally a tool, it has been reused as a surprisingly effective melee weapon, useful against smaller and/or lone enemies, or when the player is short on ammo. It is a very simple device - a length of iron or steel hexagonal rod, one end forged into a curve and furnished with a split wedge for prying nails, the other end hammered into a simple flat wedge for general prying and levering. It can be swung at a relatively fast rate and does not appear to use up stamina. The lack of ammo required aids in its use as a backup weapon.', ''),
(10, 'BFG-9000', 999999, 'https://bit.ly/2mc73dX', 'BIG FREAKING GUN', 'The BFG 9000 fires a green burst of plasma, damaging enemies near the projectile during flight and vaporising targets upon impact, as well as causing significant splash damage to enemies standing in the vicinity of the projectile\'s explosion. The damaging bolts do anywhere from 120 to 1 damage a shot at 100ms, doing 1200/1 dps. Because of the projectiles slow speed and large radius it will do major damage before the enemy leaves the area. A direct hit does 6000 damage. Thus, the BFG 9000 is the most powerful weapon in the game, as it is able to kill any non-boss creature in a single direct hit.', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cart`
--
ALTER TABLE `cart`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`orderNumber`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cart`
--
ALTER TABLE `cart`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `orderNumber` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;
--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` mediumint(8) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
